language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pyyaml
script:
  - nosetests --with-coverage --cover-erase --cover-package=cryptotranslator
after_success:
  - coveralls
